version: "3"

services:
  ngnix:
    image: nginx:stable-alpine
    networks:
      - atividade-docker
    container_name: ngnix
    ports:
      - 8080:80

  mysql:
    image: mysql:latest
    networks:
      - atividade-docker
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "docker"

networks:
  atividade-docker:
    driver: bridge
